name: ginkgo
on:
  workflow_call:
  workflow_dispatch:
  
jobs:
   build-project:
    runs-on: ubuntu-latest

    steps:
    - name: setting configurasi
      uses: actions/checkout@v3

    - name: setup environment
      run: |
          sudo apt-get update --fix-missing
          sudo apt-get install clang llvm lld gcc-aarch64-linux-gnu git make bc bison \
          openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev wget device-tree-compiler \
          ca-certificates python3 python2 binutils \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
          libghc-libyaml-dev libyaml-dev glibc-source \
    - name: ready compile...
      run: |
          chmod +x build.sh 
          ./build.sh
